import = [ "~/.config/alacritty/themes/themes/noctis-lux.toml" ]

[window]

opacity = 0.9

dimensions = { columns = 120, lines = 30}

padding = { x = 20, y = 10}

[font]

normal = { family = "Hack Nerd Font Mono", style = "Regular" }

bold = { family = "Hack Nerd Font Mono", style = "Bold" }

italic = { family = "Hack Nerd Font Mono", style = "Italic" }

bold_italic = { family = "Hack Nerd Font Mono", style = "Bold" }

size = 14

[cursor]

style = { shape = "Block", blinking = "On"}

# style.blinking = "On"
