# themes : https://github.com/alacritty/alacritty-theme
import = [ "C:\\Users\\xiashaoran\\AppData\\Roaming\\alacritty\\themes\\themes\\pencil_dark.toml" ]

[window]

opacity = 0.7

dimensions = { columns = 120, lines = 30}

# padding = { x = 10, y = 10}

[font]

normal = { family = "MartianMono Nerd Font Mono", style = "Medium" }

bold = { family = "MartianMono Nerd Font Mono", style = "Bold" }

italic = { family = "MartianMono Nerd Font Mono", style = "Italic" }

bold_italic = { family = "MartianMono Nerd Font Mono", style = "Bold" }

size = 12

[cursor]

style = { shape = "Block", blinking = "On"}

# style.blinking = "On"
